name: Build InvertOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build and export .app
      run: |
        mkdir -p output
        xcodebuild -project InvertOS.xcodeproj \
                   -scheme InvertOS \
                   -sdk iphonesimulator \
                   -configuration Release \
                   -destination 'generic/platform=iOS' \
                   build \
                   CODE_SIGNING_ALLOWED=NO

    - name: Package .app into .ipa
      run: |
        mkdir -p Payload
        cp -R build/Release-iphonesimulator/InvertOS.app Payload/
        zip -r InvertOS.ipa Payload
        mkdir -p output
        mv InvertOS.ipa output/

    - name: Upload IPA
      uses: actions/upload-artifact@3b5be7c2aa0a9242be168ec60cc69a4a51c22278
      with:
        name: InvertOS
        path: output/InvertOS.ipa
