name: Build InvertOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build InvertOS app
      run: |
        xcodebuild -project InvertOS.xcodeproj \
                   -scheme InvertOS \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   build | xcpretty
